"""Add feedback and shortcomings

Revision ID: 7cc9bea8c3d3
Revises: 20260516_0005
Create Date: 2026-05-18 12:33:46.912899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc9bea8c3d3'
down_revision: Union[str, None] = '20260516_0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('feedback_text', sa.String(length=1000), nullable=True))
    op.add_column('orders', sa.Column('shortcomings', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shortcomings')
    op.drop_column('orders', 'feedback_text')
    # ### end Alembic commands ###
