from enum import StrEnum


class OrderStatus(StrEnum):
    NEW = "NEW"
    ASSIGNED = "ASSIGNED"
    ACCEPTED = "ACCEPTED"
    ON_THE_WAY = "ON_THE_WAY"
    ARRIVED = "ARRIVED"
    IN_PROGRESS = "IN_PROGRESS"
    AWAITING_CONFIRM = "AWAITING_CONFIRM"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class IssueType(StrEnum):
    ENGINE_NOT_STARTING = "ENGINE_NOT_STARTING"
    BATTERY_DOWN = "BATTERY_DOWN"
    FLAT_TIRE = "FLAT_TIRE"
    OTHER = "OTHER"
